### ISSUE TITLE
Failed to resolve: com.halfhp.rxtracer:rxtracer:0.1.3

### ISSUE THREAD

**Issue by andrewsdv** [halfhp/rxtracer#3]
After updating Android Studio to 4.0 version and updating the following in build files:
- com.android.tools.build:gradle: to 4.0.0
- distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
for some reasons Gradle fails to resolve: com.halfhp.rxtracer:rxtracer:0.1.3:
   
> Could not find com.halfhp.rxtracer:rxtracer:0.1.3.
     Searched in the following locations:
       - https://dl.bintray.com/halfhp/rxtracer/com/halfhp/rxtracer/rxtracer/0.1.3/rxtracer-0.1.3.pom
     Required by:
         project :app

After rolling back from 4.0.0 to 3.5.3 and from gradle-5.4.1-all.zip to gradle-6.1.1-all.zip library is downloaded successfully. But it is not downloaded with new gradle plugin version.

Could you please help with this issue?

**Comment by andrewsdv** [comment]
Gradle is looking for `.pom` files which does not exist in bintray repository.
Replaced  
```
maven {
        url  "https://dl.bintray.com/halfhp/rxtracer"
    }
```
with
```
maven {
            url "https://dl.bintray.com/halfhp/rxtracer"
            metadataSources {
                mavenPom()
                artifact()
            }
        }   
```     
which is looking for `.jar` files.
Worked for me.

**Comment by halfhp** [comment]
Hey Andrew sorry for the late reply - strangely I've not experienced this issue in my own projects but I'll look into it further and either add the above to the README as updated usage instructions or bite the bullet and get the pom etc setup.

**Comment by halfhp** [comment]
Took longer than I thought but this should be fixed now.  All you need to do is update to 0.1.4
